etl:
  raw_data_file: "data/raw/Telco_customer_churn.xlsx"
  processed_path: "data/interim/"
  test_size: 0.3
  random_state: 42

train:
  processed_train: "data/train.csv"
  ensemble_model: "RandomForestClassifier"
  model_config: {n_estimators: 100, random_state: 42}
  model_path: "model/rf_model.pkl"

# train:
#   processed_train: "data/train.csv"
#   ensemble_model: "GradientBoostingClassifier"
#   model_config: {n_estimators: 100, random_state: 42}
#   model_path: "model/gb_model.pkl"

predict:
  model_path: "model/rf_model.pkl"
  processed_test: "data/test.csv"
  predicted_file: "data/predict.csv"
  export_result: True